apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-example
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-example
  template:
    metadata:
      labels:
        app: django-example
    spec:
      containers:
      - name: django-example
        image: caballeroalba/django_example:v2
        ports:
        - containerPort: 8000
